services:

  # ---- PostgreSQL ----
  postgres:
    image: postgres:16-alpine
    container_name: config-platform-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-config_platform}
      POSTGRES_USER: ${POSTGRES_USER:-config_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-config_pass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U config_user -d config_platform" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # ---- Config Server (Spring Boot) ----
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-config_platform}
      DB_USER: ${POSTGRES_USER:-config_user}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-config_pass}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  # ---- Centrifugo ----
  centrifugo:
    image: centrifugo/centrifugo:v6.7
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    # ports:
    #   - 8000-8001:8000
    #   - 10000-10001:10000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      postgres:
        condition: service_healthy
      centrifugo_redis:
        condition: service_healthy
    deploy:
      replicas: 2
    environment:
      CENTRIFUGO_ENGINE_REDIS_ADDRESS: ${CENTRIFUGO_REDIS_ADDRESS}
      CENTRIFUGO_HTTP_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_GRPC_API_KEY: ${CENTRIFUGO_API_KEY}
      CENTRIFUGO_CLIENT_TOKEN_HMAC_SECRET_KEY: ${JWT_SECRET}
      CENTRIFUGO_ADMIN_SECRET: ${CENTRIFUGO_ADMIN_SECRET}
      CENTRIFUGO_ADMIN_PASSWORD: ${CENTRIFUGO_ADMIN_PASSWORD}
      CENTRIFUGO_CONSUMERS_POSTGRES_POSTGRESQL_DSN: ${POSTGRES_DSN}

  # ---- Redis for Centrifugo ----
  centrifugo_redis:
    image: redis:8.6.2-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ---- Nginx ----
  nginx:
    image: nginx:1.29.8-alpine
    volumes:
      - ./config/nginx:/etc/nginx/templates
    depends_on:
      - centrifugo
      - config-server
    ports:
      - "8080:80"

volumes:
  pgdata:
  redis-data:
