global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: config-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - config-server:8081

  - job_name: centrifugo
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - centrifugo
        type: A
        port: 8000
        refresh_interval: 30s

  - job_name: client-sdk
    metrics_path: /actuator/prometheus
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.json
        refresh_interval: 5s
